# Generated by Django 4.1.5 on 2023-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('message', models.CharField(max_length=200)),
                ('messageTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
