# Generated by Django 4.1.5 on 2023-02-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_neuralnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuralnet',
            name='model',
        ),
    ]
