# Generated by Django 4.1.5 on 2023-02-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_neuralnet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnet',
            name='weights',
            field=models.TextField(default=None),
        ),
    ]
