# Generated by Django 4.1.5 on 2023-02-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_neuralnet_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuralnet',
            name='weights',
        ),
    ]
