# Generated by Django 4.1.5 on 2023-02-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_neuralnet_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnet',
            name='weights',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
