# Generated by Django 4.1.5 on 2023-02-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_neuralnet_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnet',
            name='accuracy',
            field=models.TextField(default=''),
        ),
    ]
