# Generated by Django 4.1.5 on 2023-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_neuralnet_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnet',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
    ]
