# Generated by Django 4.1.5 on 2023-02-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_neuralnet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnet',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
